### ISSUE TITLE
Are we meant to manually expire the unique jobs hash?

### ISSUE THREAD

**Issue by pedrocunha** [mhenrixon/sidekiq-unique-jobs#234]
Hi, thanks for this gem. We use it extensively in some of ours app. Recently we had a bunch of OOM warnings because it turns out the uniquejobs collection grew out of hand and there is no TTL on this key.

I realise that you provide an `SidekiqUniqueJobs::Util.expire` is this meant to be run periodically? Or what is the best way to ensure the unique jobs hash never grows again like this? 

I noticed that for one of our smaller apps this hash gets correctly managed. Is there some race condition? Am i missing some configuration? Is any further info I should debug?

```
> hlen uniquejobs
(integer) 835783
```

Thanks

**Comment by dennisfaust** [comment]
I ran into this same issue except we have 23M expired keys and growing. I created a Sidekiq job to delete the expired keys 2k at a time: https://gist.github.com/dennisfaust/c94f0e1aec54e37c52e431e9542ff042

**Comment by jamesr2323** [comment]
We also had this issue still with 5.0.9. For us it's related to the until_timeout lock. The recent addition of Util#expire doesn't fully clear uniquejobs if there are a lot of keys. I've submitted a PR to fix this  #236  but would be good to get to the bottom of why the uniquejobs hash builds up in the first place.

**Comment by USvER** [comment]
This is critical!!! Since my app is on heroku and using RedisToGo i have a limit of 10MB for database.
This night my app shut down just because this gem is leaking...

**Comment by AlexeyKrasnoperov** [comment]
Have the same issue too. 23239229 expired keys at the moment.
Is there any plans to release fix for it asap?

**Comment by bencrouse** [comment]
isn't this fixed by this PR? https://github.com/mhenrixon/sidekiq-unique-jobs/pull/236
maybe this issue could be closed?

**Comment by USvER** [comment]
@bencrouse so you think clearing the garbage manually is the proper fix for leaking?

**Comment by skalb** [comment]
It appears the `Util.expire` was removed--is there a better solution to clearing the keys?

**Comment by mhenrixon** [comment]
Sorry about version 5 everyone. This will be fixed in version 6. The gem should automagically just work after an upgrade and this won't be a problem anymore. There are so many improvements in v6.... everything should just work now. I will delete all gems on version 5 when version 6 is released.

Terribly sorry about version 5 everyone. I'm closing this now because version 6 is just around the corner.

**Comment by thomey** [comment]
@mhenrixon With 6.0.4, when are the hashes supposed to be deleted? Immediately after unlocking? After upgrading sidekiq-unique-jobs and deleting all the hashes manually, we're still seeing hundreds of hashes being created and never deleted in our app, which eventually will cause OOM on our Heroku Redis...

**Comment by mhenrixon** [comment]
@thomey can you be more specific, please? Sounds like your jobs are not being unlocked. There should be no leftovers anymore.

**Comment by thomey** [comment]
Sure :)

```
sidekiq-unique-jobs 6.0.4
sidekiq 5.1.3
sidekiq-cron 1.0.0
```

All `sidekiq-unique-jobs` settings are defaults. We also added this according to the docs to see if it would help:

```
Sidekiq.configure_server do |config|
  config.death_handlers << ->(job, _ex) do
      SidekiqUniqueJobs::Digests.del(digest: job['unique_digest']) if job['unique_digest']
  end
end
```

All the workers where we want locking we use the same lock mode:
`sidekiq_options lock: :until_executed, log_duplicate_payload: true`

Many of the jobs are recurring jobs using `sidekiq-cron`, running e.g. every 5 mins.

The locks seem to be released, as we can schedule new runs as long as the same worker is finished, but it just doesn't seem to be deleting the hashes from Redis.

```
irb(main):002:0> $redis.keys('uniquejobs*').count
=> 473
```

This is even when there are no active workers, so I would expect the count to be 0.

Any more info I can provide to help debugging?

**Comment by mhenrixon** [comment]
could you post what keys are left? It is the extension I am after like what is after the last `:` `uniquejobs:arandomdigest:GRABBED`. Maybe I need to delete something that isn't used.

**Comment by mhenrixon** [comment]
It would be nice to map this to the jobs in the scheduled set somehow. I'll see about finding orphaned locks for a next version.

**Comment by thomey** [comment]
Almost all of them are `AVAILABLE`, `EXISTS` and `VERSION`:
`uniquejobs:UNIQUE_HASH:AVAILABLE`
`uniquejobs:UNIQUE_HASH:EXISTS`
`uniquejobs:UNIQUE_HASH:VERSION`

I also had two that are just `uniquejobs` and `uniquejobs:UNIQUE_HASH:GRABBED`

**Comment by mhenrixon** [comment]
The keys you are mentioning are a combination of the keys needed for a successful lock. That they are there is a sign there is an active lock in redis which is nothing to worry about unless you have logs with level fatal saying. `"the unique_key: uniquejobs:randomdigest needs to be unlocked manually"`

**Comment by mhenrixon** [comment]
Ah, I see what you mean @thomey. Right now the gem is signaling to release the locks but they are kept around unless expiration is set. I don't recommend you use `lock_expiration`. I'll see what is involved in hard deleting the locks instead. I guess the lua script should delete the keys if no expiration is set and set expiration on the keys if expiration is provided.

While I'm at it I will create a script to find and delete orphaned keys also so that you don't have to manually do that.

**Comment by mhenrixon** [comment]
@thomey I just released v6.0.5 which deletes all the keys unless they are set to expire. Tell me how that works for you.

**Comment by mhenrixon** [comment]
#317

**Comment by thomey** [comment]
Looks good so far: all keys are deleted when unlocked. Thank you for the quick solution! 👍

**Comment by software-project** [comment]
@mhenrixon The issue that @thomey described before reoccured. Now all the jods are EXISTS and GRABBED. Any idea why?
